### ISSUE TITLE
GD-1072: C# Project fails to build after updating to 6.1.0

### ISSUE THREAD

**Issue by GorgWorgington** [godot-gdunit-labs/gdUnit4#1073]
### The used GdUnit4 version

6.1.0 (Latest Release)

### Godot Version

v4.6.stable.mono.official [89cea1439]

### Environment Details

Godot v4.6.stable.mono - Manjaro Linux #1 SMP PREEMPT_DYNAMIC Sun Dec  7 08:34:08 UTC 2025 on X11 - X11 display driver, Multi-window, 3 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (nvidia; 590.48.01) - 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz (12 threads) - 15.48 GiB memory

### Bug Description

I get the following compilation errors when building my project:
```
CS1061: 'Array<Dictionary>' does not contain a definition for 'Select' and no accessible extension method 'Select' accepting a first argument of type 'Array<Dictionary>' could be found (are you missing a using directive or an assembly reference?) /home/cam/dev/timebreak-studios/rite-of-osiris/addons/gdUnit4/test/dotnet/GdUnit4CSharpApiTest.cs(39,39)
```

```
CS1061: 'Array<Dictionary>' does not contain a definition for 'First' and no accessible extension method 'First' accepting a first argument of type 'Array<Dictionary>' could be found (are you missing a using directive or an assembly reference?) /home/cam/dev/timebreak-studios/rite-of-osiris/addons/gdUnit4/test/dotnet/GdUnit4CSharpApiTest.cs(161,34)
```

```
CS1061: 'Array<Dictionary>' does not contain a definition for 'First' and no accessible extension method 'First' accepting a first argument of type 'Array<Dictionary>' could be found (are you missing a using directive or an assembly reference?) /home/cam/dev/timebreak-studios/rite-of-osiris/addons/gdUnit4/test/dotnet/GdUnit4CSharpApiTest.cs(168,34)
```

I was able to get it to build by just adding `using System.Linq;` to the top of the file.

### Steps to Reproduce

Try to build a C# project.

**Comment by GorgWorgington** [comment]
I was able to solve my problem by pointing godotenv to the zip file on the releases page. You can close this issue if you don't think the build errors are worth investigating.

**Comment by MikeSchulze** [comment]
Thanks for response, btw. GdUnit4 has his own update tooling.
Closing this isse because of not API relevant, i will verify the test and fix if need.
